import React from 'react'
import Head from 'next/head'

export const HeadPage = () => {
  return (
       <Head>
        <title>Dir Repo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  )
}
