/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head'
import api from '../api'
import ProjectList from '../components/ProjectList'
import { Header } from '../components/Header'
import { Project } from '../types'
import type { GetStaticProps } from 'next'
interface Props {
  projects: Project[]
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const projects = await api.projects.list()
  return {
    props: {
      projects
    }
  }
}

const Home = ({ projects }: Props) => {
  return (
    <main className='w-auto flex flex-col items-center bg-slate-800'>
      <Head>
        <title>Dir Repo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <ProjectList projects={projects}/>
    </main>
  )
}

export default Home
